version: "3"

services:
  app:
    build: .
    container_name: starter
    ports:
      - 8000:8000
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - APP_SECRET_KEY=j7w0sd!v5!clacym&c@22ha9jby61z+gz3urs-!az(+@0790u(
      - APP_ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
      - APP_LANG_CODE=en
      - APP_TIME_ZONE=UTC
      - APP_USE_TIME_ZONE=true
      - APP_AUTO_MIGRATE=false
      - DB_DATABASE=starter
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - GUNICORN_APP=starter.wsgi:application
      - GUNICORN_WORKER=4
      - GUNICORN_HOST=0.0.0.0
      - GUNICORN_PORT=8000
      - GUNICORN_RELOAD=true
    volumes:
      - ./src:/code/src
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: app-pgsql
    environment:
      - POSTGRES_DB=starter
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - "54321:5432"
    volumes:
      - app-pg-data:/var/lib/postgresql/data

volumes:
  app-pg-data:
